source ~/.vim_machine_specific.vim
source ~/.config/nvim/plug.vim
source ~/.config/nvim/settings.vim
source ~/.config/nvim/autocmd.vim
source ~/.config/nvim/coc_fzf.vim
source ~/.config/nvim/command.vim
source ~/.config/nvim/plug_settings.vim
source ~/.config/nvim/plug_remap.vim
source ~/.config/nvim/statusline.vim
source ~/.config/nvim/abbr.vim
source ~/.config/nvim/remap.vim
